version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Liquibase

      # Clean old install
      - rm -rf /opt/liquibase liquibase*

      # Download
      - curl -L https://github.com/liquibase/liquibase/releases/download/v4.25.1/liquibase-4.25.1.tar.gz -o liquibase.tar.gz

      # Extract
      - tar -xzf liquibase.tar.gz

      # Find extracted folder
      - LIQUIBASE_DIR=$(ls -d liquibase-* | head -n 1)

      # Install
      - mv "$LIQUIBASE_DIR" /opt/liquibase

      # Make executable
      - chmod +x /opt/liquibase/liquibase

      # Add to PATH
      - ln -sf /opt/liquibase/liquibase /usr/local/bin/liquibase

      # Install jq
      - yum install -y jq

      # Verify
      - liquibase --version


  pre_build:
    commands:
      - echo Fetching DB credentials

      - SECRET=$(aws secretsmanager get-secret-value --region eu-north-1 --secret-id prod/appbeta/rds/mysql --query SecretString --output text)

      - export DB_USER=$(echo "$SECRET" | jq -r .username)
      - export DB_PASS=$(echo "$SECRET" | jq -r .password)
      - export DB_HOST=$(echo "$SECRET" | jq -r .host)
      - export DB_PORT=$(echo "$SECRET" | jq -r .port)

      - echo DB Host is $DB_HOST
      - echo DB Port is $DB_PORT


  build:
    commands:
      - echo Running Liquibase

      - liquibase \
          --url="jdbc:postgresql://$DB_HOST:$DB_PORT/postgres" \
          --username="$DB_USER" \
          --password="$DB_PASS" \
          --changeLogFile=db/changelog/db.changelog-master.xml \
          update
