version: 0.2

env:
  variables:
    # Set these in CodeBuild "Environment variables" or via Parameter Store/Secrets Manager
    CHANGELOG_FILE: "liquibase/changelog/master.xml"
    LIQUIBASE_URL: ""          # e.g., jdbc:postgresql://<host>:5432/<db>
    LIQUIBASE_USERNAME: ""     # e.g., liquibase_user
    LIQUIBASE_DEFAULT_SCHEMA_NAME: ""  # optional
    # For security, DO NOT put passwords in plaintext. Use PARAMETER_STORE/SECRETS_MANAGER instead.
  # parameter-store:
  #   LIQUIBASE_PASSWORD: "/myapp/db/liquibase_password"  # example path in SSM Parameter Store

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:      
      - set -euo pipefail
      - echo "Installing Prerequisites"
      - yum install -y jq
      - curl -L https://github.com/liquibase/liquibase/releases/download/v4.25.1/liquibase-4.25.1.tar.gz -o liquibase.tar.gz
      - mkdir -p /opt/liquibase
      - tar -xzf liquibase.tar.gz -C /opt/liquibase
      - ln -sf /opt/liquibase/liquibase /usr/local/bin/liquibase
      - echo "==> Downloading PostgreSQL JDBC driver"
      - export PG_JDBC_VERSION=42.7.3
      - curl -L -o /opt/liquibase/lib/postgresql-${PG_JDBC_VERSION}.jar "https://jdbc.postgresql.org/download/postgresql-${PG_JDBC_VERSION}.jar"
      # Verify      
      - java -version
      - liquibase --version


  # pre_build:
  #   commands:
  #     - echo "Fetching DB credentials"

  #     - SECRET=$(aws secretsmanager get-secret-value --region eu-north-1 --secret-id prod/appbeta/rds/mysql --query SecretString --output text)

  #     - export DB_USER=$(echo "$SECRET" | jq -r .username)
  #     - export DB_PASS=$(echo "$SECRET" | jq -r .password)
  #     - export DB_HOST=$(echo "$SECRET" | jq -r .host)
  #     - export DB_PORT=$(echo "$SECRET" | jq -r .port)

  #     - echo "DB Host is $DB_HOST"
  #     - echo "DB Port is $DB_PORT"
  #     - echo "==> Working directory: $(pwd)"

  build:
    commands:
      - echo "Running Liquibase"

      - pwd
      - ls -R .
      - ls -R liquibase || true
      - ls -R liquibase/changelog || true

      - liquibase --log-level=FINE \
        --url="jdbc:postgresql://database-1.cf8a8aiigobn.eu-north-1.rds.amazonaws.com:5432/postgres" \
        --username="postgres"\
        --password="x27!I!4gW31Vjhl" \
        --changeLogFile="liquibase/changelog/master.xml" \
        update

cache:
  paths:
    - '/opt/liquibase/**/*'
