version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Liquibase"
      - curl -L https://github.com/liquibase/liquibase/releases/download/v4.25.1/liquibase-4.25.1.zip -o liquibase.zip
      - unzip liquibase.zip -d liquibase
      - curl -L https://jdbc.postgresql.org/download/postgresql-42.7.3.jar -o liquibase/lib/postgresql.jar
      - export PATH=$PATH:$(pwd)/liquibase

  build:
    commands:
      - echo "Running Liquibase update"
      - |
        liquibase \
          --url=jdbc:postgresql://$DB_HOST:$DB_PORT/$DB_NAME \
          --username=$DB_USERNAME \
          --password=$DB_PASSWORD \
          --changeLogFile=liquibase/changelog/master.xml \
          update
